<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="2">

  <testsuite name="checkInscription"
    errors="0" failures="1" hostname="" id="" package="checkInscription" skipped="0"
    tests="2" time="31.13" timestamp="Mon, 25 Apr 2016 11:51:39 GMT">
  
    <testcase name="should warn the user that the inscription is not correct" time="17.91" assertions="1">

    
    </testcase>
  
    <testcase name="should show the download button with correct data" time="13.23" assertions="1">  <failure message="Testing if element &lt;#checkInscriptionFormContent &gt; div.alert.alert-success.animated.fadeInDown&gt; is present.">    at Object.module.exports.should show the download button with correct data (C:\Users\Emilio\nightwhatch\src\tests\checkInscription.js:14:19)
    at Module.call (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:63:34)
    at C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:97:29
    at _fulfilled (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Emilio\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
